using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ClassGenerator;

namespace GeneratedTestClass.Test
{
    [TestClass]
    public class GeneratedTestClassTests
    {
        [TestMethod]
        public void WritesomethingTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void LolkekCheburekTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}