using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyTestSpace;

namespace MyClass.Test
{
    [TestClass]
    public class MyClassTests
    {
        [TestMethod]
        public void MyMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}